gear/urls.py
from django.urls import path
from gear.views.home import home_view
from .views.add import add_item_view, add_collection_view, add_library_view
from gear.views.detail import item_detail_view, collection_detail_view
from gear.views.detail import library_detail_view
from gear.views.requests.rentals.librarian_rental_view import (
    librarian_rentals,
    approve_rental_request,
    deny_rental_request,
    currently_borrowed_items_view,
    return_items_view,
)
from gear.views.requests.private_collection.librarian_private_collections_view import (
    librarian_private_collections,
)
from gear.views.requests.rentals.patron_rental_view import (
    patron_rentals,
    patron_borrowing_history,
)

app_name = "gear"

urlpatterns = [
    path("", home_view.home, name="home"),
    path("add/item", add_item_view.add_item, name="add_item"),
    path("add/collection", add_collection_view.add_collection, name="add_collection"),
    path("add/library", add_library_view.add_library, name="add_library"),
    path("item/<uuid:item_id>/", item_detail_view.item_detail, name="item_detail"),
    path("item/<uuid:item_id>/edit/", item_detail_view.edit_item, name="item_edit"),
    path(
        "item/<uuid:item_id>/delete/", item_detail_view.delete_item, name="item_delete"
    ),
    path(
        "collections/<uuid:collection_id>/",
        collection_detail_view.collection_detail,
        name="collection_detail",
    ),
    path(
        "collection/<uuid:collection_id>/edit/",
        collection_detail_view.edit_collection,
        name="edit_collection",
    ),
    path(
        "collection/<uuid:collection_id>/delete/",
        collection_detail_view.delete_collection,
        name="delete_collection",
    ),
    path(
        "libraries/<uuid:library_id>/",
        library_detail_view.library_detail,
        name="library_detail",
    ),
    path(
        "libraries/<uuid:library_id>/edit/",
        library_detail_view.edit_library,
        name="edit_library",
    ),
    path(
        "libraries/<uuid:library_id>/delete/",
        library_detail_view.delete_library,
        name="delete_library",
    ),
    path(
        "librarian/currently-borrowed/",
        currently_borrowed_items_view,
        name="librarian_currently_borrowed",
    ),
    path(
        "librarian/return-item/",
        return_items_view,
        name="librarian_return_items",
    ),
    path(
        "patron/borrowing-history/",
        patron_borrowing_history,
        name="patron_borrowing_history",
    ),
]

gearup/urls.py
from django.contrib import admin
from django.urls import include, path

import users

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('social_django.urls', namespace='social')),
    path('users/', include('users.urls')),
    path('', include('gear.urls')),
]

users/urls.py
from django.urls import path

from gear.views.detail import collection_detail_view, item_detail_view
from gear.views.home import home_view
from gear.views.requests.rentals import librarian_rental_view, patron_rental_view
from gear.views.requests.private_collection import (
    patron_private_collections_view,
    librarian_private_collections_view,
)
from gear.views.wishlist import wishlist_view
from .views import base_view
from .views.librarian import add_librarian_view
from .views import profile_view

app_name = "users"

urlpatterns = [
    path("logout/", base_view.logout_view, name="logout"),
    path("profile/", profile_view.profile, name="profile"),
    path("librarian/add/", add_librarian_view.add_librarian, name="add_librarian"),
    path("update_profile/", profile_view.update_user, name="update_profile"),
    path("wishlist/", wishlist_view.wishlist, name="wishlist"),
    path(
        "item/<uuid:item_id>/add_to_wishlist/",
        home_view.add_to_wishlist,
        name="add_to_wishlist",
    ),
    path(
        "wishlist/remove/<uuid:item_id>/",
        wishlist_view.remove_from_wishlist,
        name="remove_from_wishlist",
    ),
    path(
        "request_rent_item/<uuid:item_id>/",
        item_detail_view.request_rent_item,
        name="request_rent_item",
    ),
    path("patron/rentals/", patron_rental_view.patron_rentals, name="patron_rentals"),
    path(
        "requests/rentals/<uuid:request_id>/cancel/",
        patron_rental_view.cancel_request,
        name="cancel_rental_request",
    ),
    path(
        "librarian/rentals/",
        librarian_rental_view.librarian_rentals,
        name="librarian_rentals",
    ),
    path(
        "librarian/rentals/<uuid:request_id>/approve/",
        librarian_rental_view.approve_rental_request,
        name="approve_rental_request",
    ),
    path(
        "librarian/rentals/<uuid:request_id>/deny/",
        librarian_rental_view.deny_rental_request,
        name="deny_rental_request",
    ),
    path(
        "request_private_collection/<uuid:collection_id>/",
        collection_detail_view.request_private_collection,
        name="request_private_collection",
    ),
    path(
        "patron/private_collections/",
        patron_private_collections_view.patron_private_collections,
        name="patron_private_collections",
    ),
    path(
        "patron/private_collections/<uuid:request_id>/cancel/",
        patron_private_collections_view.cancel_private_collection_request,
        name="cancel_private_collection_request",
    ),
    path(
        "librarian/private_collections/",
        librarian_private_collections_view.librarian_private_collections,
        name="librarian_private_collections",
    ),
    path(
        "librarian/private_collections/<uuid:request_id>/approve/",
        librarian_private_collections_view.approve_private_collection_request,
        name="approve_private_collection_request",
    ),
    path(
        "librarian/private_collections/<uuid:request_id>/deny/",
        librarian_private_collections_view.deny_private_collection_request,
        name="deny_private_collection_request",
    ),
    path(
        "leave_review/<uuid:item_id>/",
        item_detail_view.leave_review,
        name="leave_review",
    ),
]

gear/forms/add_collection_form.py
from django import forms
from gear.forms.base_form import BaseForm
from gear.models import Item
from users.models import UserProfile
from users.service.service_instances import _patron_service
from gear.views.base import is_librarian


class CollectionForm(BaseForm):
    image = forms.ImageField(required=False)

    is_private = forms.BooleanField(
        required=False,
        label="Private Collection",
        widget=forms.CheckboxInput(
            attrs={
                "class": "w-6 h-6 border-2 border-gray-300 focus:ring-2 focus:ring-primary focus:outline-none duration-200 ease-in-out checked:bg-primary checked:border-transparent shadow-sm"
            }
        ),
    )

    allowed_users = forms.ModelMultipleChoiceField(
        queryset=UserProfile.objects.none(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    items = forms.ModelMultipleChoiceField(
        queryset=None,
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        self.request_user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if self.request_user:
            self.fields[
                "allowed_users"
            ].queryset = _patron_service.get_all_patrons().exclude(
                email=self.request_user.email
            )

        self.fields["items"].queryset = Item.objects.all()

        if not is_librarian(self.request_user):
            self.fields["items"].queryset = (
                self.fields["items"]
                .queryset.filter(collections__is_private=False)
                .distinct()
            )

gear/forms/add_item_form.py
from django import forms

from gear.forms.base_form import BaseForm


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

    def value_from_datadict(self, data, files, name):
        return files.getlist(name)


class MultipleFileField(forms.FileField):
    widget = MultipleFileInput

    def clean(self, data, initial=None):
        if not data:
            return []
        if isinstance(data, (list, tuple)):
            return [super(MultipleFileField, self).clean(f, initial) for f in data]
        return [super(MultipleFileField, self).clean(data, initial)]


class ItemForm(BaseForm):
    LOCATION_CHOICE = [
        ("", "Location..."),
        ("in_store", "In Store"),
        ("online", "Online"),
    ]
    location = forms.ChoiceField(
        choices=LOCATION_CHOICE,
        required=True,
        error_messages={"required": "Please select a location."},
        widget=forms.Select(
            attrs={
                "class": "w-25 h-12 pr-3 text-left rounded-lg border-1 border-gray-300 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
            }
        ),
    )
    quantity = forms.IntegerField(
        min_value=1,
        max_value=9999,
        required=True,
        error_messages={
            "required": "Please enter a quantity.",
            "min_value": "Quantity must be at least 1.",
            "max_value": "Quantity cannot be larger than 9999. Please enter a smaller number.",
        },
        widget=forms.NumberInput(
            attrs={
                "placeholder": "Quantity",
                "class": "w-full h-12 pr-3 text-left rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent",
            }
        ),
    )
    images = MultipleFileField(
        required=False, help_text="You can upload multiple images."
    )

gear/forms/add_library_form.py
from django import forms
from gear.forms.base_form import BaseForm
from gear.models import Collection, Item
from users.models import UserProfile
from gear.service.service_instances import _item_service, _collection_service
from django.db.models import Q


class LibraryForm(BaseForm):
    image = forms.ImageField(required=False)

    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    collections = forms.ModelMultipleChoiceField(
        queryset=Collection.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        self.request_user = kwargs.pop("user", None)
        item_search_query = kwargs.pop("item_search_query", "")
        collection_search_query = kwargs.pop("collection_search_query", "")
        super().__init__(*args, **kwargs)

        items_qs = _item_service.get_all_items()
        collections_qs = _collection_service.get_all_collections()

        if item_search_query:
            items_qs = items_qs.filter(
                Q(title__icontains=item_search_query)
                | Q(description__icontains=item_search_query)
            )

        if collection_search_query:
            collections_qs = collections_qs.filter(
                Q(title__icontains=collection_search_query)
                | Q(description__icontains=collection_search_query)
            )

        self.fields["items"].queryset = items_qs
        self.fields["collections"].queryset = collections_qs

gear/forms/base_form.py
from django import forms


class BaseForm(forms.Form):
    title = forms.CharField(
        max_length=50,
        required=True,
        error_messages={"required": "Please enter a Title."},
        widget=forms.TextInput(
            attrs={
                "placeholder": "Title",
                "class": "w-full px-4 h-12 rounded-lg border-1 border-gray-300 focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary",
            }
        ),
    )
    description = forms.CharField(
        max_length=500,
        required=True,
        error_messages={"required": "Please enter a Description."},
        widget=forms.Textarea(
            attrs={
                "placeholder": "Description",
                "class": "w-full px-4 rounded-lg border-1 border-gray-300 focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary h-[6rem] max-h-[12rem] resize-y",
                "rows": 4,
                "style": "padding-top: 8px; resize: none;",
            }
        ),
    )

gear/forms/request_rental_form.py
from django import forms


class Request_Rental_Form(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        required=True,
        error_messages={"required": "Please enter a quantity."},
        widget=forms.NumberInput(
            attrs={
                "placeholder": "Rental Quantity",
                "class": "w-25 h-12 pr-3 text-left rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent",
            }
        ),
    )

gear/forms/review_form.py
from django import forms
from gear.models import ItemReview


class ReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, i) for i in range(1, 6)],
        widget=forms.HiddenInput(attrs={"class": "focus:ring"}),
        required=True,
    )
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={"rows": 3, "class": "textarea textarea-bordered w-full"}
        ),
        required=False,
    )

    class Meta:
        model = ItemReview
        fields = ["rating", "comment"]

gear/views/base.py
from users.service.service_instances import _librarian_service, _patron_service
from django.shortcuts import render
from ..models import Collection


def is_librarian(user):
    return _librarian_service.is_librarian(user)


def is_patron(user):
    return _patron_service.is_patron(user)


def collection_detail(request, collection_id):
    collection = Collection.objects.get(id=collection_id)
    if collection.created_by and is_patron(collection.created_by.userprofile):
        creator_text = f"Created by {collection.created_by.userprofile.name}"
    else:
        creator_text = "Created by GearUp"

    context = {
        "collection": collection,
        "creator_text": creator_text,
    }
    return render(request, "your_template.html", context)

gear/templates/components/_collection_private_request_card_librarian.html
{% load static %}
{% load tz %}
<div class="relative card bg-base-100 rounded-xl overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col h-full">
  <a href="{% url 'gear:collection_detail' access_request.collection.id %}" class="flex-grow">
    <figure class="aspect-[4/3] bg-gray-100 overflow-hidden relative flex items-center justify-center">
      <img src="{{ access_request.collection.image.url }}" alt="{{ access_request.collection.title }}" class="max-w-full max-h-full object-contain" />
      <div class="absolute top-4 left-4">
        {% if access_request.status == 'pending' %}
          <span class="badge badge-warning text-xs font-medium">Pending</span>
        {% elif access_request.status == 'approved' %}
          <span class="badge badge-success text-xs font-medium">Approved</span>
        {% elif access_request.status == 'rejected' %}
          <span class="badge badge-error text-xs font-medium">Denied</span>
        {% endif %}
      </div>
    </figure>
    <div class="card-body p-6 flex flex-col justify-between">
      <div>
        <div class="flex justify-between items-start mb-2">
          <div class="badge badge-outline text-xs font-bold text-primary border-primary">Collection Request</div>
          <div class="text-sm text-gray-500">{{ access_request.request_date|localtime|date:'M d, Y g:i A' }}</div>
        </div>
        <h2 class="card-title text-lg font-bold mb-2">{{ access_request.collection.title }}</h2>
        <p class="text-sm text-gray-600 mb-1">Patron: {{ access_request.patron.name }}</p>
        {% if access_request.status == 'approved' %}
          <p class="text-sm text-success">
            <i class="bi bi-check-circle mr-1"></i>Approved on: {{ access_request.approved_date|date:'M d, Y' }}
          </p>
          <p class="text-sm text-gray-600">Approved by: {{ access_request.approved_by.name }}</p>
        {% elif access_request.status == 'rejected' %}
          <p class="text-sm text-error">
            <i class="bi bi-x-circle mr-1"></i>Denied on: {{ access_request.request_date|localtime|date:'M d, Y g:i A' }}
          </p>
          <p class="text-sm text-gray-600">Denied by: {{ access_request.approved_by.name }}</p>
        {% endif %}
      </div>
    </div>
  </a>

  {% if access_request.status == 'pending' %}
    <div class="card-actions justify-end p-4 border-t border-gray-100">
      <label for="approve-modal-{{ access_request.id }}" class="btn bg-white text-success border-success btn-sm hover:text-white hover:bg-success">Approve <i class="bi bi-hand-thumbs-up"></i></label>
      <label for="deny-modal-{{ access_request.id }}" class="btn bg-white text-error border-error btn-sm hover:text-white hover:bg-error">Deny <i class="bi bi-hand-thumbs-down"></i></label>
    </div>

    <input type="checkbox" id="approve-modal-{{ access_request.id }}" class="modal-toggle" />
    <div class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Approve Private Collection Request</h3>
        <p class="py-4">
          Are you sure you want to approve the request for <strong>{{ access_request.collection.title }}</strong> by {{ access_request.patron.name }}?
        </p>
        <div class="modal-action">
          <label for="approve-modal-{{ access_request.id }}" class="btn btn-outline">Cancel</label>
          <form method="POST" action="{% url 'users:approve_private_collection_request' access_request.id %}" class="approve-request-form disable-on-submit">
            {% csrf_token %}
            <button data-disable-on-submit type="submit" class="btn bg-white text-success border-success hover:text-white hover:bg-success">Approve Request <i class="bi bi-hand-thumbs-up"></i></button>
          </form>
        </div>
      </div>
      <label class="modal-backdrop" for="approve-modal-{{ access_request.id }}"></label>
    </div>

    <input type="checkbox" id="deny-modal-{{ access_request.id }}" class="modal-toggle" />
    <div class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Deny Private Collection Request</h3>
        <p class="py-4">
          Are you sure you want to deny the request for <strong>{{ access_request.collection.title }}</strong> by {{ access_request.patron.name }}?
        </p>
        <div class="modal-action">
          <label for="deny-modal-{{ access_request.id }}" class="btn btn-outline">Cancel</label>
          <form method="POST" action="{% url 'users:deny_private_collection_request' access_request.id %}" class="deny-request-form disable-on-submit">
            {% csrf_token %}
            <button data-disable-on-submit type="submit" class="btn bg-red-500 text-white hover:bg-red-600">Deny Request <i class="bi bi-hand-thumbs-down"></i></button>
          </form>
        </div>
      </div>
      <label class="modal-backdrop" for="deny-modal-{{ access_request.id }}"></label>
    </div>
  {% endif %}
</div>

gear/templates/components/_collection_private_request_card_patron.html
{% load gear_filters %}
<div class="card bg-base-100 rounded-xl overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col relative">
  <a href="{% url 'gear:collection_detail' access_request.collection.id %}" class="block">
    <figure class="aspect-[4/3] bg-gray-100 overflow-hidden flex items-center justify-center">
      <img src="{{ access_request.collection.image.url }}" alt="{{ access_request.collection.title }}" class="max-w-full max-h-full object-contain" />
    </figure>
    <div class="card-body p-6 flex flex-col justify-between">
      <div>
        <h2 class="card-title text-lg font-bold mb-2">{{ access_request.collection.title }}</h2>
        <p class="text-sm text-gray-600 mb-3">{{ access_request.collection.description|truncatechars:80 }}</p>
        <div class="text-xs">
          <span class="badge {% if access_request.status == 'pending' %}
              
              
            badge-warning


            {% elif access_request.status == 'approved' %}
              
              
            badge-success


            {% elif access_request.status == 'rejected' %}
              
              
            badge-error


            {% endif %}">
            {{ access_request.status|capfirst }}
          </span>
        </div>
      </div>
    </div>
  </a>
  {% if access_request.status == 'pending' %}
    <div class="absolute bottom-4 right-4 z-50">
      <label for="cancel-modal-{{ access_request.id }}" class="btn btn-outline btn-error btn-sm hover:text-white" onclick="event.stopPropagation()">Cancel</label>
      <input type="checkbox" id="cancel-modal-{{ access_request.id }}" class="modal-toggle" />
      <div class="modal">
        <div class="modal-box">
          <h3 class="font-bold text-lg">Cancel Private Collection Request</h3>
          <p class="py-4">Are you sure you want to cancel your request for {{ access_request.collection.title }}?</p>
          <div class="modal-action">
            <label for="cancel-modal-{{ access_request.id }}" class="btn btn-outline">Keep Request</label>
            <form method="POST" action="{% url 'users:cancel_private_collection_request' access_request.id %}" class="cancel-request-form disable-on-submit">
              {% csrf_token %}
              <button data-disable-on-submit type="submit" class="btn bg-red-500 text-white hover:bg-red-600">Cancel Request</button>
            </form>
          </div>
        </div>
        <label class="modal-backdrop" for="cancel-modal-{{ access_request.id }}"></label>
      </div>
    </div>
  {% elif access_request.status == 'rejected' %}
    <div class="absolute bottom-4 right-4 z-10">
      <form action="{% url 'users:request_private_collection' access_request.collection.id %}" method="POST" style="display:inline;" class="disable-on-submit">
        {% csrf_token %}
        <button data-disable-on-submit type="submit" class="btn btn-success text-lg">Request Again <i class="bi bi-rocket-takeoff"></i></button>
      </form>
    </div>
  {% endif %}
</div>

gear/templates/components/_item_rental_librarian_card.html
{% load static %}
{% load tz %}
<div class="relative card bg-base-100 rounded-xl overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col h-full">
  <a href="{% url 'gear:item_detail' request.item.id %}" class="flex-grow">
    <figure class="aspect-[4/3] bg-gray-100 overflow-hidden relative flex items-center justify-center">
      <img src="{{ request.item.get_first_image }}" alt="{{ request.item.title }}" class="max-w-full max-h-full object-contain" />
      <div class="absolute top-4 left-4">
        {% if request.status == 'pending' %}
          <span class="badge badge-warning text-xs font-medium">Pending</span>
        {% elif request.status == 'approved' %}
          <span class="badge badge-success text-xs font-medium">Approved</span>
        {% elif request.status == 'rejected' %}
          <span class="badge badge-error text-xs font-medium">Denied</span>
        {% endif %}
      </div>
    </figure>
    <div class="card-body p-6 flex flex-col justify-between">
      <div>
        <div class="flex justify-between items-start mb-2">
          <div class="badge badge-outline text-xs font-bold text-success border-emerald-200">Rental Request</div>
          <div class="text-sm text-gray-500">{{ request.request_date|localtime|date:'M d, Y g:i A' }}</div>
        </div>
        <h2 class="card-title text-lg font-bold mb-2">{{ request.item.title }}</h2>
        <p class="text-sm text-gray-600 mb-1">Patron: {{ request.patron.name }}</p>
        <p class="text-sm text-gray-600 mb-3">Quantity: {{ request.quantity }}</p>

        {% if request.status == 'approved' %}
          <p class="text-sm text-success">
            <i class="bi bi-check-circle mr-1"></i>Approved on: {{ request.approved_date|date:'M d, Y' }}
          </p>
          <p class="text-sm text-gray-600">Approved by: {{ request.approved_by.name }}</p>
        {% elif request.status == 'rejected' %}
          <p class="text-sm text-error">
            <i class="bi bi-x-circle mr-1"></i>Denied on: {{ request.request_date|localtime|date:'M d, Y g:i A' }}
          </p>
          <p class="text-sm text-gray-600">Denied by: {{ request.approved_by.name }}</p>
        {% endif %}
      </div>
    </div>
  </a>

  {% if request.status == 'pending' %}
    <div class="card-actions justify-end p-4 border-t border-gray-100">
      <label for="approve-modal-{{ request.id }}" class="btn bg-white text-success border-success btn-sm hover:text-white hover:bg-success">Approve <i class="bi bi-hand-thumbs-up"></i></label>
      <label for="deny-modal-{{ request.id }}" class="btn bg-white text-error border-error btn-sm hover:text-white hover:bg-error">Deny <i class="bi bi-hand-thumbs-down"></i></label>
    </div>

    <input type="checkbox" id="approve-modal-{{ request.id }}" class="modal-toggle" />
    <div class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Approve Rental Request</h3>
        <p class="py-4">Are you sure you want to approve the request for {{ request.quantity }} {{ request.item.title }} by {{ request.patron.name }}?</p>
        <p class="text-sm text-gray-600">
          Available quantity: {{ request.item.available_quantity }}
          {% if request.quantity > request.item.available_quantity %}
            <span class="text-error">(Not enough available)</span>
          {% endif %}
        </p>
        <div class="modal-action">
          <label for="approve-modal-{{ request.id }}" class="btn btn-outline">Cancel</label>
          <form method="POST" action="{% url 'users:approve_rental_request' request.id %}" class="approve-request-form disable-on-submit">
            {% csrf_token %}
            <button data-disable-on-submit type="submit" class="btn bg-white text-success border-success hover:text-white hover:bg-success">Approve Request<i class="bi bi-hand-thumbs-up"></i></button>
          </form>
        </div>
      </div>
      <label class="modal-backdrop" for="approve-modal-{{ request.id }}"></label>
    </div>

    <input type="checkbox" id="deny-modal-{{ request.id }}" class="modal-toggle" />
    <div class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Deny Rental Request</h3>
        <p class="py-4">Are you sure you want to deny the request for {{ request.quantity }} {{ request.item.title }} by {{ request.patron.name }}?</p>
        <div class="modal-action">
          <label for="deny-modal-{{ request.id }}" class="btn btn-outline">Cancel</label>
          <form method="POST" action="{% url 'users:deny_rental_request' request.id %}" class="deny-request-form disable-on-submit">
            {% csrf_token %}
            <button data-disable-on-submit type="submit" class="btn bg-red-500 text-white hover:bg-red-600">Deny Request<i class="bi bi-hand-thumbs-down"></i></button>
          </form>
        </div>
      </div>
      <label class="modal-backdrop" for="deny-modal-{{ request.id }}"></label>
    </div>
  {% endif %}
</div>

gear/templates/components/_item_rental_patron_card.html
{% load static %}
{% load tz %}

<div class="relative">
  <a href="{% url 'gear:item_detail' request.item.id %}" class="card bg-base-100 rounded-xl overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-300 hover:-translate-y-1 flex flex-col h-full">
    <figure class="aspect-[4/3] bg-gray-100 overflow-hidden relative flex items-center justify-center">
      <img src="{{ request.item.get_first_image }}" alt="{{ request.item.title }}" class="max-w-full max-h-full object-contain" />
      <div class="absolute top-4 left-4">
        {% if request.status == 'pending' %}
          <span class="badge badge-warning text-xs font-medium">Pending</span>
        {% elif request.status == 'approved' %}
          <span class="badge badge-success text-xs font-medium text-white">Approved</span>
        {% elif request.status == 'rejected' %}
          <span class="badge badge-error text-xs font-medium">Denied</span>
        {% endif %}
      </div>
    </figure>
    <div class="card-body p-6 flex flex-col justify-between">
      <div>
        <div class="flex justify-between items-start mb-2">
          <div class="badge badge-outline text-xs font-bold text-success border-emerald-200">Rental Request</div>
          <div class="text-sm text-gray-500">{{ request.request_date|localtime|date:'M d, Y g:i A' }}</div>
        </div>
        <h2 class="card-title text-lg font-bold mb-2">{{ request.item.title }}</h2>
        <p class="text-sm text-gray-600 mb-3">Quantity: {{ request.quantity }}</p>
        {% if request.status == 'approved' %}
          <p class="text-sm text-success">
            <i class="bi bi-check-circle mr-1"></i>Approved on: {{ request.approved_date|date:'M d, Y' }}
          </p>
        {% endif %}
      </div>
    </div>
  </a>
  {% if request.status == 'pending' %}
    <div class="absolute bottom-4 right-4 z-50">
      <label for="cancel-modal-{{ request.id }}" class="btn btn-outline btn-error btn-sm hover:text-white" onclick="event.stopPropagation()">Cancel</label>
      <input type="checkbox" id="cancel-modal-{{ request.id }}" class="modal-toggle" />
      <div class="modal">
        <div class="modal-box">
          <h3 class="font-bold text-lg">Cancel Rental Request</h3>
          <p class="py-4">Are you sure you want to cancel your request for {{ request.quantity }} {{ request.item.title }}?</p>
          <div class="modal-action">
            <label for="cancel-modal-{{ request.id }}" class="btn btn-outline">Keep Request</label>
            <form method="POST" action="{% url 'users:cancel_rental_request' request.id %}" class="cancel-request-form disable-on-submit">
              {% csrf_token %}
              <button data-disable-on-submit type="submit" class="btn bg-red-500 text-white hover:bg-red-600">Cancel Request</button>
            </form>
          </div>
        </div>
        <label class="modal-backdrop" for="cancel-modal-{{ request.id }}"></label>
      </div>
    </div>
  {% elif request.status == 'rejected' %}
    <div class="absolute bottom-4 right-4 z-10">
      <form action="{% url 'users:request_rent_item' request.item.id %}" method="POST" style="display:inline;" class="disable-on-submit">
        {% csrf_token %}
        <input type="hidden" name="quantity" value="{{ request.quantity }}" />
        <button data-disable-on-submit type="submit" class="btn btn-success text-lg">Request Again <i class="bi bi-rocket-takeoff"></i></button>
      </form>
    </div>
  {% endif %}
</div>

gear/templates/components/_star_rating.html
{% for group, options, index in widget.optgroups %}
    {% for option in options %}
        <input type="radio" name="{{ widget.name }}" value="{{ option.value }}" 
               class="mask mask-star-2 bg-orange-400" id="{{ option.attrs.id }}"
               {% if option.selected %}checked{% endif %}>
    {% endfor %}
{% endfor %}